#pragma once

#define IDC_TOOLSLIST 1
#define IDC_TITLE     2   

#define IDC_INFO_VERSION_TITLE  100
#define IDC_INFO_VERSION        101
#define IDC_INFO_BOT_TITLE      102
#define IDC_INFO_BOT_KEY_TITLE  103
#define IDC_INFO_BOT_KEY        104
#define IDC_INFO_BOT_INFO_TITLE 105
#define IDC_INFO_BOT_INFO       106
#define IDC_INFO_BOT_REFRESH    107
#define IDC_INFO_BOT_REMOVE     108

#define IDC_BUILDER_SOURCE_TITLE  100
#define IDC_BUILDER_SOURCE        101
#define IDC_BUILDER_SOURCE_BROWSE 102
#define IDC_BUILDER_SOURCE_EDIT   103
#define IDC_BUILDER_BUILD_TITLE   104
#define IDC_BUILDER_BUILD_CONFIG  105
#define IDC_BUILDER_BUILD_BOT     106
#define IDC_BUILDER_BUILD_OUTPUT  107

#define IDC_SETTINGS_LANGUAGE_TITLE 100
#define IDC_SETTINGS_LANGUAGE       101
#define IDC_SETTINGS_APPLY          102

#define DIALOG_MAIN           1
#define DIALOG_TOOL_INFO      2
#define DIALOG_TOOL_BUILDER   3
#define DIALOG_TOOL_SETTINGS  4

#define ICON_MAIN 1
